module.exports = {
  mySidebar: [
    'index',
    'release-notes',
    {
      type: 'category', 
      label: 'Installation',
      collapsed: true,
      items: [
        'installation/introduction',
        'installation/pre-installation-worksheet',
        'installation/copy-installation-files',
        'installation/automated-installation-upgrade',
        'installation/new-installation',
        'installation/upgrade-installation',
      ], 
    },
    {
      type: 'category', 
      label: 'Configuration',
      collapsed: true,
      items: [
        'configuration/mcp-lsam-configuration',
        'configuration/configuration-settings',
        'configuration/general-lsam-configuration',
        'configuration/communication-parameters',
        'configuration/processing-variables',
        'configuration/optional-modules',
        'configuration/update-max-concurrent-jobs',
        'configuration/set-up-failure-status-message',
      ], 
    },
    {
      type: 'category', 
      label: 'Operations and Components',
      collapsed: true,
      items: [
        'operations-and-components/mcp-lsam-operation',
        {
          type: 'category', 
          label: 'SMA/MANAGER',
          collapsed: true,
          items: [
            'operations-and-components/sma-manager/sma-manager-overview',
            'operations-and-components/sma-manager/general-lsam-configuration',
            'operations-and-components/sma-manager/communication-parameters',
            'operations-and-components/sma-manager/processing-variables',
            'operations-and-components/sma-manager/optional-modules',
            'operations-and-components/sma-manager/status',
            'operations-and-components/sma-manager/initiate-the-lsam',
            'operations-and-components/sma-manager/resource-monitor',
            'operations-and-components/sma-manager/inquire-display-msg-backlog',
            'operations-and-components/sma-manager/lsam-debugging',
            'operations-and-components/sma-manager/reload',
            'operations-and-components/sma-manager/displays-definition-maintenance-menu',
            'operations-and-components/sma-manager/displays-definition-file-maintenance',
            'operations-and-components/sma-manager/file-monitoring-definition-file-maintenance',
            'operations-and-components/sma-manager/resource-monitoring-definition-file-maintenance',
            'operations-and-components/sma-manager/restore-configuration-and-definition-files',
            'operations-and-components/sma-manager/error-and-informational-messages',
            'operations-and-components/sma-manager/transaction-server-utility',
          ], 
        },
        'operations-and-components/core-programs-and-files',
        'operations-and-components/optional-programs-and-files',
        'operations-and-components/additional-files-and-impact',
      ], 
    },
    {
      type: 'category', 
      label: 'Additional Features',
      collapsed: true,
      items: [
        'additional-features/lsam-feature-overview',
        {
          type: 'category', 
          label: 'LSAM Features',
          collapsed: true,
          items: [
            'additional-features/lsam-features/automated-response',
            'additional-features/lsam-features/command-line-interface-utility',
            'additional-features/lsam-features/data-collector-for-mcp',
            'additional-features/lsam-features/dynamic-lsam-configuration',
            'additional-features/lsam-features/external-event-interface-library',
            'additional-features/lsam-features/external-jobs-tracking',
            'additional-features/lsam-features/file-monitor',
            'additional-features/lsam-features/file-transfer',
            'additional-features/lsam-features/installation-utility',
            'additional-features/lsam-features/interactive-lsam-window',
            'additional-features/lsam-features/jors',
            'additional-features/lsam-features/msgin',
            'additional-features/lsam-features/multiple-lsams',
            'additional-features/lsam-features/operations-monitor',
            'additional-features/lsam-features/resource-monitor',
            'additional-features/lsam-features/resource-utilization-statistics',
            'additional-features/lsam-features/user-defined-restart-checkpoints',
          ], 
        },
        {
          type: 'category', 
          label: 'MCP LSAM Utilities',
          collapsed: true,
          items: [
            'additional-features/utilities/mcp-lsam-utilities',
            'additional-features/utilities/file-arrival-utility',
            'additional-features/utilities/sma-syntax-check',
            'additional-features/utilities/sma-wfl-check-mix',
            'additional-features/utilities/sma-wfl-change',
            'additional-features/utilities/sma-wfl-cleanup-linc17-files',
            'additional-features/utilities/sma-wfl-command',
            'additional-features/utilities/sma-wfl-convert-print',
            'additional-features/utilities/sma-wfl-copy',
            'additional-features/utilities/sma-wfl-filecheck',
            'additional-features/utilities/sma-wfl-filecount',
            'additional-features/utilities/sma-wfl-processcheck',
            'additional-features/utilities/sma-wfl-remove',
            'additional-features/utilities/sma-resource-check',
          ], 
        },
      ], 
    },
    'debugging',
    {
      type: 'category', 
      label: 'Reference Information',
      collapsed: true,
      items: [
        'reference-information/machine-messages',
        'reference-information/file-monitor-messages',
        'reference-information/sma-file-transfer-messages',
        'reference-information/mcp-known-issues',
        {
          type: 'category', 
          label: 'Troubleshooting',
          collapsed: true,
          items: [
            'reference-information/troubleshooting/troubleshooting',
            'reference-information/troubleshooting/auto-response',
            'reference-information/troubleshooting/communication',
            'reference-information/troubleshooting/configuration',
            'reference-information/troubleshooting/file-monitoring',
            'reference-information/troubleshooting/file-transfer',
            'reference-information/troubleshooting/job-initiation-monitoring',
            'reference-information/troubleshooting/jors',
            'reference-information/troubleshooting/lsam-initialization-stopping',
            'reference-information/troubleshooting/mcp-job-flow',
          ], 
        },
        'reference-information/legacy',
        'reference-information/communication-parameters-legacy',
        'reference-information/processing-variables-legacy',
        'reference-information/optional-modules-legacy',
      ], 
    },
  ],
};
